backend:
  name: git-gateway # test-repo
  branch: main # Branch to update (optional; defaults to master)
local_backend: true
media_folder: public/img
public_folder: img
collections:
  - name: news
    label: News
    label_singular: "News"
    folder: _posts
    slug: "{{slug}}"
    media_folder: ""
    public_folder: ""
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Excerpt
        name: excerpt
        widget: string
      - label: Author
        name: author
        widget: string
      - label: Date
        name: date
        widget: date
      - { label: "Body", name: "body", widget: "markdown" }
  - name: daniele
    label: Den
    label_singular: "Game"
    folder: _users/daniele
    slug: "{{slug}}"
    media_folder: ""
    public_folder: ""
    create: true
    fields:
      - label: Title
        name: title
        widget: string
  - name: aurelie
    label: Aure
    label_singular: "Game"
    folder: _users/aurelie
    slug: "{{slug}}"
    media_folder: ""
    public_folder: ""
    create: true
    fields:
      - label: Slug
        name: slug
        widget: string
      - label: Excerpt
        name: excerpt
        widget: string
      - label: BGG ID
        name: bggId
        widget: string
      - label: Rating
        name: rating
        widget: string
      - label: Purchased Date
        name: date
        widget: date
      - { label: "Body", name: "body", widget: "markdown" }
