backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  identity_url: "https://condescending-visvesvaraya-a0b270.netlify.app/.netlify/identity"
  gateway_url: "https://condescending-visvesvaraya-a0b270.netlify.app/.netlify/git"

local_backend: true
media_folder: public/img
public_folder: img
collections:
  - name: "users"
    label: "Users"
    files:
      - label: "User"
        name: "daniele"
        file: "daniele/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Hot"
            name: "hot"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
